<!DOCTYPE html>
<!--
/*
* Fayl menjr Akbarali tomonidan yozildi.
* Johncms Profile Link: https://johncms.com/profile/?user=38217
* Those who want to sponsor: Webmoney WMR: R853215959425, Webmoney WMZ: Z401474330355, Webmoney WMY: Y194307290426
*/
-->
<html>

<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title><?= $title; ?></title>
    <!-- Include our stylesheet -->
    <link rel="stylesheet" href="<?= $this->asset('editor/css/styles.css', true) ?>">
    <script src="<?= $this->asset('/editor/js/winbox.bundle.js', true) ?>"></script>
    <script src="<?= $this->asset('/editor/js/kitchen-sink/require.js', true) ?>"></script>
    <script src="<?= $this->asset('/editor/js/hotkeys.js', true) ?>"></script>
    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="https://ace.c9.io/build/src-noconflict/ace.js"></script>
    <script src="https://cloud9ide.github.io/emmet-core/emmet.js"></script>
    <script src="https://ace.c9.io/build/src-noconflict/ext-language_tools.js"></script>
</head>

<body>
    <style type="text/css" media="screen">
        .ace_editor {
            border: 1px solid lightgray;
            margin: auto;
            height: 200px;
            width: 80%;
        }

        .scrollmargin {
            height: 80px;
            text-align: center;
        }

        img:hover {
            background: wheat;
            cursor: pointer;
        }
    </style>
    <?php if (DEMO_VERSION === true) :   ?>
        <!-- TOP LEFT RIBBON: START COPYING HERE -->
        <a class="github-fork-ribbon left-bottom fixed" href="https://github.com/akbarali1/johncms-commander" data-ribbon="Fork me on GitHub" title="Fork me on GitHub">Fork me on GitHub</a>
        <!-- TOP LEFT RIBBON: END COPYING HERE -->
    <?php endif; ?>
    <div class="filemanager">
        <div class="search">
            <input type="search" placeholder="Find a file.." />
        </div>
        <div class="breadcrumbs"></div>
        <ul class="data" id="fayllar"></ul>
        <div class="nothingfound">
            <div class="nofiles"></div>
            <span>No files here.</span>
        </div>
    </div>
    <footer>
        <img src="<?= $this->asset('editor/icons/svg/add-file.svg') ?>" alt="new file" onclick="newfile();" title="new file" class="rightmenu">
        <img src="<?= $this->asset('editor/icons/svg/new-folder.svg') ?>" alt="new file" onclick="newfolder();" title="new folder" class="rightmenu">
    </footer>
    <script src="<?= $this->asset('/editor/js/script.js', true) ?>"></script>
    <input type="hidden" id="foldername">
    <input type="hidden" id="ochilganeditor">
</body>

</html>