<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VS Code Editor</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="<?= $this->asset('editor/css/styles.css', true) ?>">
    <link rel="stylesheet" href="<?= $this->asset('editor/css/stylevscode.css', true) ?>">
    <script src="<?= $this->asset('/editor/js/winbox.bundle.js', true) ?>"></script>
    <script src="<?= $this->asset('/editor/js/winbox.bundle.js', true) ?>"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.7/jstree.min.js"></script>
    <script src="https://cloud9ide.github.io/emmet-core/emmet.js"></script>
    <script src="https://ace.c9.io/build/src-noconflict/ace.js"></script>
    <script src="https://ace.c9.io/build/src-noconflict/ext-language_tools.js"></script>
    <script src="<?= $this->asset('/editor/js/kitchen-sink/require.js', true) ?>"></script>
    <script src="<?= $this->asset('/editor/js/hotkeys.js', true) ?>"></script>

</head>
<style>
    img.topimages:hover {
        opacity: 0.4;
    }
</style>

<body style=" background: #2c2b2b; color: #b2b2b2; ">
    <a class="github-fork-ribbon right-bottom" href="https://github.com/akbarali1/johncms-commander" data-ribbon="Fork me on GitHub" title="Fork me on GitHub">Fork me on GitHub</a>
    <div class="container-fluid">
        <div class="row px-3">
            <div class="col-lg-2 col-md-2 col-2" style="height: 941px;overflow: scroll;max-height: 100%;padding-left: 0;font-size: 14px;">
                <div class="row" style="display: block;padding-right: 10px;padding-left: 56%;background: #494949;">
                    <img class="topimages" src="\themes\default\assets\editor\icons\newfile.png" id="newfile" onclick="newfile();" style=" width: 30px; padding: 0; margin: 0; ">
                    <img class="topimages" src="\themes\default\assets\editor\icons\newfolder.png" id="newfolder" onclick="newfolder();" style=" width: 30px; padding: 0; margin: 0; ">
                    <img class="topimages" src="\themes\default\assets\editor\icons\refresh.png" id="newfolder" onclick="reloadFiles();" style=" width: 30px; padding: 0; margin: 0; ">
                    <img class="topimages" src="\themes\default\assets\editor\icons\close.png" id="newfolder" onclick="jstreeToggleState();" style="width: 30px;padding: 0;margin: 2px;">
                </div>
                <div id="files">
                    <div class="card-block"><?= $main_dir ?></div>
                </div>
            </div>
            <div class="col-10">
            </div>
        </div>
    </div>
    </div>
    <script src="<?= $this->asset('/editor/js/vscode.js', true) ?>"></script>
    <input type="hidden" id="openfilename">
    <input type="hidden" name="clickfoldername" id="clickfoldername">
    <input type="hidden" id="ochilganeditor">
    <input type="hidden" name="clickfilename" id="clickfilename">
    <input type="hidden" name="hozirclick" id="hozirclick">

</body>

</html>